---
- hosts: all

  become: yes
  become_method: sudo
  remote_user: ubuntu

  tasks:
    - name: install prerequsites
      apt:
        name: python-software-properties
        state: present
    - name: install rep
      apt_repository:
        repo: 'ppa:deadsnakes/ppa'
        state: present
    - name: Install mysql
      apt:
        name: mysql-server
