---
- hosts: all

  become: yes
  become_method: sudo
  remote_user: ubuntu

  tasks:
  - name: Update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 #One day

  - name: install putty
    apt:
      update_cache: yes
      name:  putty
      state: present
